version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pidor
      POSTGRES_USER: pidor
    ports:
      - 5434:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8700:8080